#*  This playbook simply wrapps the file module. It simulates the
#* famous CLI tools 'echo -n ""/rm/rmdir'. If the target is a file,
#* it will be emptied, if it is a dir, any file or subdir will be
#* removed.
#*  As this simplifies both the tools and the file module usage,
#* some features will possibly be missing.
#*  The following arguments are mandatory:
#*   - 'path' (aliases: 'dest', 'name', 'file', 'dir')
#*  The following arguments are optional:
#*

- hosts: all
  vars:
    path: '{{ file | d(dest) | d(name) | d(dir) }}'
  roles:
    - file-empty
