#*  This playbook simply wrapps the fetch module. Per default it gets
#* a certain file from the server and puts it in the workdir.
#*  The following arguments are mandatory:
#*   - 'files'
#* Maestro Example:
#*    `$ maestro.sh -f -H bup00 play get 'files=["/etc/hosts","/etc/network/interfaces"]'

- hosts: all

  roles:
    - fetch
