#*  This playbook wrapps the apt (and others maybe in the future..) module
#* to install software needed on a physical host ('bare metal').
#*  Note: this playbook should be used either from the main install playbook
#* (which resolves its dependencies) or as a shorthand for an already set up
#* system, where the dependencies are already provided.
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  No arguments are mandatory.

- hosts: host.Metal

  roles:
    - zwischenloesung.yapkg
  vars:
    - yapkg_group_name: 'on a physical machine'
    - yapkg_names:
      - 'kpartx'
      - 'lm-sensors'
      - 'lshw'
      - 'smartmontools'

# not enabling this yet, as it only tracks 'today'
# it is only useful for human communication and needs
# to be combined with something smarter as
# dpkg --get-selections
#- hosts: all

#  roles:
#    - track-packages

