#*  This playbook wrapps the apt (and others maybe in the future..) module
#* to install software considered basic here - i.e. to be installed on every
#* host (non minimal/embedded..). It is the first one in the row and thus
#* has no dependencies.
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  No arguments are mandatory.

- include: install-sudo.yml
- include: install-fail2ban.yml
- include: deploy-accounts-store.yml
- include: install-ssh.yml
- include: install-terminal-mux.yml

- hosts: app.basics
  become: true
  roles:
    - inofix.yapkg
    - install-vim
  vars:
    - yapkg__task_group_name: 'basic software'
    - yapkg__names:
      - 'apt-show-versions'
      - 'cron-apt'
      - 'gawk'
      - 'git'
      - 'htop'
      - 'iotop'
      - 'less'
      - 'lsb-release'
      - 'nmon'
      - 'strace'
      - 'xml2'

- hosts: app.ntpdate
  become: true
  roles:
    - inofix.yapkg
  vars:
    - yapkg__task_group_name: 'basic software'
    - yapkg__names:
      - 'ntpdate'
      - 'ntp'

# not enabling this yet, as it only tracks 'today'
# it is only useful for human communication and needs
# to be combined with something smarter as
# dpkg --get-selections
#- hosts: all

#  roles:
#    - track-packages

