#*  This playbook wrapps the apt (and others maybe in the future..) module
#* to install software for managing archives, that are not installed
#* automatically or as basic software.
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  No arguments are mandatory.

- hosts: app.archive
  become: True
  roles:
    - { role: inofix.yapkg, yapkg__task_group_name: 'archive', yapkg__names: [ 'bzip2', 'unzip', 'xz-utils', 'zip' ] }

# not enabling this yet, as it only tracks 'today'
# it is only useful for human communication and needs
# to be combined with something smarter as
# dpkg --get-selections
#- hosts: all

#  roles:
#    - track-packages

