#*  This playbook wrapps the apt (and others maybe in the future..) module
#* to install software considered basic here - i.e. to be installed on every
#* host (non minimal/embedded..). It is the first one in the row and thus
#* has no dependencies.
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  No arguments are mandatory.

# Get the host ready for ansible, only 'raw' method is available..
- hosts: os.debian
  become: true
  become_method: "su"
  gather_facts: false
  tasks:
    - name: "Make sure python2 is installed on this debian host: check for the command"
      raw: 'test -e {{ ansible_python_interpreter }}'
      ignore_errors: true
      register: is_python_installed
    - name: "Make sure python2 is installed on this debian host: install it"
      raw: 'apt -y update && apt install -y python2'
      when: is_python_installed.rc != 0

- include: install-sudo.yml
- include: deploy-accounts-store.yml
- include: install-ssh.yml
- include: install-terminal-mux.yml

- hosts: app.basics
  become: true
  roles:
    - inofix.yapkg
    - install-vim
  vars:
    - yapkg__task_group_name: 'basic software'
    - yapkg__names:
      - 'apt-show-versions'
      - 'cron-apt'
      - 'gawk'
      - 'git'
      - 'htop'
      - 'iotop'
      - 'less'
      - 'lsb-release'
      - 'nmon'
      - 'ntpdate'
      - 'ntp'
      - 'strace'
      - 'xml2'

# not enabling this yet, as it only tracks 'today'
# it is only useful for human communication and needs
# to be combined with something smarter as
# dpkg --get-selections
#- hosts: all

#  roles:
#    - track-packages

