#*  This playbook wrapps the apt (and others maybe in the future..) module
#* to install at least fail2ban on public servers with ssh exposed..
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  No arguments are mandatory.

- hosts: app.fail2ban, &app.sshd
  become: true
  roles:
    - inofix.yapkg
    - setup-fail2ban
  vars:
    - yapkg__task_group_name: 'fail2ban software'
    - yapkg__names:
      - 'fail2ban'

# not enabling this yet, as it only tracks 'today'
# it is only useful for human communication and needs
# to be combined with something smarter as
# dpkg --get-selections
#- hosts: all

#  roles:
#    - track-packages

