#*  This playbook wrapps the apt (and others maybe in the future..) module
#* to install `incron` and (currently only on Debian bullseye-backports.)
#* It is the first one in the row and thus has no dependencies.
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  No arguments are mandatory.

- hosts: app.incron, &os.debian_bullseye
  become: true
  roles:
    - add-backports
    - inofix.yapkg
  vars:
    - yapkg__task_group_name: 'incron'
    - yapkg__names: '{{ os__pkg_name.incron[os__distro][os__codename] | d([ "incron" ]) }}'

# not enabling this yet, as it only tracks 'today'
# it is only useful for human communication and needs
# to be combined with something smarter as
# dpkg --get-selections
#- hosts: all

#  roles:
#    - track-packages

