---
nextcloud__name: '{{ app__nextcloud__name | d(default__nextcloud__name) }}'
nextcloud__home: '{{ app__nextcloud__home | d(default__nextcloud__home) }}'
nextcloud__data: '{{ app__nextcloud__data | d(default__nextcloud__data) }}'

d__nextcloud__config: '{{ nextcloud__home }}/config/config.php'
d__nextcloud__autoconfig: '{{ nextcloud__home }}/config/autoconfig.php'
nextcloud__config: '{{ app__nextcloud__config | d(d__nextcloud__config) }}'
nextcloud__autoconfig: '{{ app__nextcloud__autoconfig | d(d__nextcloud__autoconfig) }}'
nextcloud__yapkg__names: '{{ app__nextcloud__yapkg__names }}'
nextcloud__user: '{{ app__nextcloud__user | d(default__nextcloud__user) }}'
nextcloud__group: '{{ app__nextcloud__group | d(default__nextcloud__group) }}'

nextcloud__db_host: '{{ app__nextcloud__db_host | d(default__nextcloud__db_host) }}'
nextcloud__db_tableprefix: '{{ app__nextcloud__db_tableprefix | d(default__nextcloud__db_tableprefix) }}'
nextcloud__db_credentials_key: '{{ app__nextcloud__db_credentials_key | d(default__nextcloud__db_credentials_key) }}'
nextcloud__db_credentials_name: '{{ app__nextcloud__db_credentials_name | d(default__nextcloud__db_credentials_name) }}'
nextcloud__db_type: '{{ app__nextcloud__db_type | d(default__nextcloud__db_type) }}'
nextcloud__db_name: '{{ app__nextcloud__db_name | d(default__nextcloud__db_name) }}'
nextcloud__db_user: '{{ app__nextcloud__db_user | d(default__nextcloud__db_user) }}'
nextcloud__admin_user: '{{ app__nextcloud__admin_user | d(default__nextcloud__admin_user) }}'
nextcloud__admin_credentials_key: '{{ app__nextcloud__admin_credentials_key | d(default__nextcloud__admin_credentials_key) }}'
nextcloud__admin_credentials_name: '{{ app__nextcloud__admin_credentials_name | d(default__nextcloud__admin_credentials_name) }}'
nextcloud__db_pass_placeholder: '{{ app__nextcloud__db_pass_placeholder | d(app__nextcloud__db_pass_placeholder) }}'
nextcloud__admin_pass_placeholder: '{{ app__nextcloud__admin_pass_placeholder | d(app__nextcloud__admin_pass_placeholder) }}'

postgresql__edit_db: '{{ app__postgresql__edit_db | d(default__postgresql__edit_db) }}'
postgresql__user: '{{ app__postgresql__user | d(default__postgresql__user) }}'
postgresql__encrypt_password: '{{ app__postgresql__encrypt_password | d(default__postgresql__encrypt_password) }}'

