# In a first 'quick' version 'virt-install' will be used to install debian variants via preseed and custom scripts..

- name: 'Test variables'
  fail:
    msg: 'Some mandatory variable was missing..'
  when: new.domainname is not defined or new.default_password is not defined or new.net is not defined or new.net.eth0 is not defined or new.net.eth0.ip is not defined or new.net.eth0.netmask is not defined or new.net.eth0.gateway is not defined

- name: 'Check that the new host really is defined as virtual'
  fail:
    msg: '{{ new__hostname }} is not defined as virtual in new.type'
  when: new.type != 'vm'

#- name: prepare a logical volume for storage
#  lvol:
#    lv: '{{ new__hostname }}'
#    size: '{{ virt.storage.default.size }}'
#    vg: '{{ virt.storage.default.pool }}'

- name: 'Check if a virtual machine with the same name is already defined'
  stat:
    path: '/etc/libvirt/qemu/{{ new__hostname }}.xml'
  register: vm_def

#- name: 'Check if a virtual machine with the same name already exists'
#  virt:
#    command: list_vms
#  register: result

#- name: "foo"
#  debug:
#    var: result

- name: 'Prepare the (temp.?) working directory hierarchy'
  file:
    path: '{{ os__tmp_image_dir }}'
    state: directory
    mode: '0755'

- name: 'Download the netinstaller files'
  environment:
    http_proxy: '{{ http_proxy }}'
  get_url:
    url: '{{ item.url }}'
    dest: '{{ item.dest }}'
    checksum: '{{ item.checksum }}'
  with_items: '{{ os__installer_files[new.arch] }}'

- name: 'Install the preseed template'
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items: '{{ os__installer_templates }}'

- name: 'Create a virtual machine'
  shell: 'virt-install --quiet --connect {{ host.virt.connect }} --autostart --noautoconsole --console pty,target_type=serial --virt-type {{ host.virt.type }} --name {{ new__hostname }} --vcpus {{ new.cpu.cores }} --ram {{ new.mem.size }} --disk pool={{ new.disk.system.meta.pool }},size={{ new.disk.system.size }},format={{ host.virt.storage[new.disk.system.meta.pool].format }},cache={{ host.virt.storage[new.disk.system.meta.pool].cache }} --network {{ host.virt.network }} --os-type {{ new.os.distro }} --os-variant {{ new.os.variant }} --video {{ host.virt.display.video }} --graphics {{ host.virt.display.graphics }} --location {{ os__tmp_installer_dir }} --initrd-inject={{ os__installer_template_list | join(" --initrd-inject=") }} --extra-args "{{ host.virt.install_console }} auto=true file=/preseed.cfg hostname={{ new__hostname }} domain={{ new.domainname }} interface=auto netcfg/get_ipaddress={{ new.net.eth0.ip }} netcfg/get_netmask={{ new.net.eth0.netmask }} netcfg/get_gateway={{ new.net.eth0.gateway }} netcfg/get_nameservers={{ new.net.eth0.nameserver }} netcfg/confirm_static=true netcfg/disable_dhcp=true" --debug'
  when: ( vm_def.stat.isreg is not defined )

