
# add it in a controlled way..

- name: "add the backports repo: {{ os__codename }}"
  apt_repository:
    repo: "{{ os__repository.backports.deb }}"
    state: present
  when: ansible_os_family == "Debian" and ansible_distribution_release == "{{ os__codename }}"
  register: deb_backports_added

- name: update the repository index
  apt:
    update_cache: yes
  when: deb_backports_added

