---
# Assumption: Use a separate AllowUsers line for every case
- name: Define AllowUsers to let our admins in (and them only)
  lineinfile:
    insertafter: '^AllowUsers (.*)$'
    line: 'AllowUsers {% for u in admins %}{{ u }} {% endfor %}'
    dest: '{{ app__sshd__config | d(sshd_config) }}'
    state: present
  when: admins is iterable

# Assumption: If real users are present, there is no need to login as root
- name: Disable root login altogether
  lineinfile:
    regexp: '^PermitRootLogin .*$'
    line: 'PermitRootLogin no'
    dest: '{{ app__sshd__config | d(sshd_config) }}'
    state: present
  when: admins is iterable

- name: Set the port
  lineinfile:
    regexp: '^Port .*$'
    line: 'Port {{ app__sshd__port }}'
    dest: '{{ app__sshd__config | d(sshd_config) }}'
    state: present
