---

- name: Install a cron job to be run in the background
  cron:
    minute: "*/5*"
    hour: "*"
    day: "*"
    weekday: "*"
    month: "*"
    user: '{{ nextcloud__user }}'
    job: '[ -r {{ nextcloud__home }}/cron.php ] && php {{ nextcloud__home }}/cron.php'

